# Generated by Django 5.2.15 on 2026-06-14 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_level_scene_dialogue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialogue',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='order',
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='scene',
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='speaker',
        ),
        migrations.AddField(
            model_name='dialogue',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogues', to='api.character'),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.dialogue'),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
