# Generated by Django 5.2.15 on 2026-06-15 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dialogue_options_remove_dialogue_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='api.scene'),
        ),
    ]
