# Generated by Django 5.2.15 on 2026-06-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dialogue_scene'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Player', max_length=50)),
                ('theme', models.CharField(choices=[('neon', 'Neon'), ('aqua', 'Aqua'), ('light', 'Light')], default='neon', max_length=20)),
            ],
        ),
    ]
