# Generated by Django 5.2.15 on 2026-06-25 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Project', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('dimension', models.CharField(blank=True, default='', max_length=2)),
                ('genre', models.CharField(blank=True, default='', max_length=30)),
                ('systems', models.JSONField(blank=True, default=dict)),
                ('hud_layout', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='level',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='api.project'),
        ),
    ]
