# Generated by Django 5.2.15 on 2026-06-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_default_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('neon', 'Neon'), ('aqua', 'Aqua'), ('light', 'Light'), ('studio', 'Studio')], default='neon', max_length=20),
        ),
    ]
