# Generated by Django 5.2.15 on 2026-07-01 22:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AddField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='character',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='api.project'),
        ),
        migrations.AddField(
            model_name='character',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_as_a', to='api.character')),
                ('character_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_as_b', to='api.character')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('character_a', 'character_b'), name='uniq_char_pair')],
            },
        ),
    ]
