# Generated by Django 5.2.15 on 2026-07-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_directed_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
