# Generated by Django 5.2.15 on 2026-07-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_character_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
