# Generated by Django 5.2.15 on 2026-07-02 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_character_image_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image_url',
        ),
    ]
