# Generated by Django 5.2.15 on 2026-07-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_character_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='effects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='state_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
