/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate the user (placeholder)
         * @description Placeholder for future authentication.
         *
         *     Always returns HTTP 400 and is intentionally NOT called by the frontend yet.
         */
        post: operations["api_api_auth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user */
        get: operations["api_api_get_current_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the current user */
        patch: operations["api_api_update_current_user"];
        trace?: never;
    };
    "/api/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List characters */
        get: operations["api_api_list_characters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["api_api_list_projects"];
        put?: never;
        /** Create a project */
        post: operations["api_api_create_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a project */
        get: operations["api_api_get_project"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a project
         * @description Partial update: rename, Settings (dimension/genre), Systems, or Preview (hud_layout).
         */
        patch: operations["api_api_update_project"];
        trace?: never;
    };
    "/api/levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List levels
         * @description All levels, or just one project's levels when `project_id` is given.
         */
        get: operations["api_api_list_levels"];
        put?: never;
        /** Create a level */
        post: operations["api_api_create_level"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/levels/{level_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a level */
        get: operations["api_api_get_level"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a level */
        patch: operations["api_api_update_level"];
        trace?: never;
    };
    "/api/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List scenes */
        get: operations["api_api_list_scenes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dialogues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List root dialogues
         * @description Root dialogues (no parent). Pass `scene_id` to get the roots for one scene.
         */
        get: operations["api_api_list_root_dialogues"];
        put?: never;
        /**
         * Create a dialogue
         * @description Create a dialogue node. Pass `parent_id` to attach it as a response of another node.
         */
        post: operations["api_api_create_dialogue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dialogues/{dialogue_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a dialogue
         * @description A dialogue with its character and immediate responses (its children).
         */
        get: operations["api_api_get_dialogue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a dialogue
         * @description Partial update: only the fields present in the request body are changed.
         */
        patch: operations["api_api_update_dialogue"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Error */
        Error: {
            /** Error */
            error: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Theme */
            theme: string;
        };
        /**
         * UserUpdateIn
         * @description Partial update of the current user (e.g. their selected theme).
         */
        UserUpdateIn: {
            /** Name */
            name?: string | null;
            /** Theme */
            theme?: string | null;
        };
        /** CharacterOut */
        CharacterOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * ProjectOut
         * @description A game project plus its game-wide config (settings/systems/HUD).
         */
        ProjectOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Order */
            order: number;
            /** Dimension */
            dimension: string;
            /** Genre */
            genre: string;
            /**
             * Systems
             * @default {}
             */
            systems: {
                [key: string]: unknown;
            };
            /**
             * Hud Layout
             * @default {}
             */
            hud_layout: {
                [key: string]: unknown;
            };
        };
        /** ProjectCreateIn */
        ProjectCreateIn: {
            /**
             * Name
             * @default New Project
             */
            name: string;
            /** Order */
            order?: number | null;
        };
        /**
         * ProjectUpdateIn
         * @description Partial update — omitted fields are left unchanged. One PATCH serves rename,
         *     Settings (dimension/genre), Systems, and Preview (hud_layout) saves.
         */
        ProjectUpdateIn: {
            /** Name */
            name?: string | null;
            /** Order */
            order?: number | null;
            /** Dimension */
            dimension?: string | null;
            /** Genre */
            genre?: string | null;
            /** Systems */
            systems?: {
                [key: string]: unknown;
            } | null;
            /** Hud Layout */
            hud_layout?: {
                [key: string]: unknown;
            } | null;
        };
        /** LevelOut */
        LevelOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Order */
            order: number;
            /** Project Id */
            project_id?: number | null;
        };
        /** LevelCreateIn */
        LevelCreateIn: {
            /**
             * Name
             * @default New Level
             */
            name: string;
            /** Order */
            order?: number | null;
            /** Project Id */
            project_id?: number | null;
        };
        /**
         * LevelUpdateIn
         * @description Partial update of a level (e.g. its title).
         */
        LevelUpdateIn: {
            /** Name */
            name?: string | null;
            /** Order */
            order?: number | null;
        };
        /** SceneOut */
        SceneOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Level Id */
            level_id: number;
            /** Level Name */
            level_name: string;
        };
        /**
         * DialogueSummaryOut
         * @description Lightweight dialogue used for root lists and response cards.
         */
        DialogueSummaryOut: {
            /** Id */
            id: number;
            /** Text */
            text: string;
            character?: components["schemas"]["CharacterOut"] | null;
        };
        /**
         * DialogueDetailOut
         * @description The current dialogue plus its immediate responses (the wheel).
         */
        DialogueDetailOut: {
            /** Id */
            id: number;
            /** Text */
            text: string;
            /** Scene Id */
            scene_id?: number | null;
            /** Parent Id */
            parent_id?: number | null;
            character?: components["schemas"]["CharacterOut"] | null;
            /**
             * Responses
             * @default []
             */
            responses: components["schemas"]["DialogueSummaryOut"][];
        };
        /**
         * DialogueIn
         * @description Payload to create a dialogue (optionally as a response of `parent_id`).
         */
        DialogueIn: {
            /** Scene Id */
            scene_id?: number | null;
            /** Parent Id */
            parent_id?: number | null;
            /** Character Id */
            character_id?: number | null;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /**
         * DialogueUpdateIn
         * @description Partial update — omitted fields are left unchanged.
         */
        DialogueUpdateIn: {
            /** Character Id */
            character_id?: number | null;
            /** Text */
            text?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_api_auth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_api_get_current_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    api_api_update_current_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    api_api_list_characters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterOut"][];
                };
            };
        };
    };
    api_api_list_projects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    api_api_create_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    api_api_get_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    api_api_update_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    api_api_list_levels: {
        parameters: {
            query?: {
                project_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelOut"][];
                };
            };
        };
    };
    api_api_create_level: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LevelCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelOut"];
                };
            };
        };
    };
    api_api_get_level: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                level_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelOut"];
                };
            };
        };
    };
    api_api_update_level: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                level_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LevelUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelOut"];
                };
            };
        };
    };
    api_api_list_scenes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneOut"][];
                };
            };
        };
    };
    api_api_list_root_dialogues: {
        parameters: {
            query?: {
                scene_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogueSummaryOut"][];
                };
            };
        };
    };
    api_api_create_dialogue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DialogueIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogueDetailOut"];
                };
            };
        };
    };
    api_api_get_dialogue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialogue_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogueDetailOut"];
                };
            };
        };
    };
    api_api_update_dialogue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialogue_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DialogueUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogueDetailOut"];
                };
            };
        };
    };
}
